### ISSUE TITLE
Bug Report: Uhhh compiling issues

### ISSUE THREAD

**Issue by CasualCypress** [Blantados/BETADCIU-Engine-Source#10]
source/flxanimate/animate/FlxSymbol.hx:116: characters 75-80 : error: Int should be String
source/flxanimate/animate/FlxSymbol.hx:116: characters 75-80 :  have: Null<Int>
source/flxanimate/animate/FlxSymbol.hx:116: characters 75-80 :  want: haxe.extern.EitherType<String, ...>
source/flxanimate/animate/FlxSymbol.hx:116: characters 75-80 : For function argument 'name'
source/flxanimate/animate/FlxSymbol.hx:116: characters 61-82 : Void should be Array<flxanimate.animate.FlxLayer>
source/flxanimate/animate/FlxSymbol.hx:100: characters 34-39 : error: Int should be String
source/flxanimate/animate/FlxSymbol.hx:100: characters 34-39 :  have: Null<Int>
source/flxanimate/animate/FlxSymbol.hx:100: characters 34-39 :  want: haxe.extern.EitherType<String, ...>
source/flxanimate/animate/FlxSymbol.hx:100: characters 34-39 : For function argument 'name'
source/flxanimate/animate/FlxTimeline.hx:96: characters 25-29 : error: flxanimate.animate.FlxLayer should be Int
source/flxanimate/animate/FlxTimeline.hx:96: characters 25-29 :  have: haxe.extern.EitherType<..., flxanimate.animate.FlxLayer>
source/flxanimate/animate/FlxTimeline.hx:96: characters 25-29 :  want: haxe.extern.EitherType<..., Int>
source/flxanimate/animate/FlxTimeline.hx:96: characters 25-29 : For function argument 'name'

what do i need to install to make this stop happening

**Comment by Blantados** [comment]
Compile with new commit. I forgot to remove FlxAnimate as it's still experimental.
