### ISSUE TITLE
Bug Report: Compiling update issues

### ISSUE THREAD

**Issue by icaroleeb** [Blantados/BETADCIU-Engine-Source#11]
![image](https://user-images.githubusercontent.com/89704810/216771046-896962ea-48aa-4516-96a3-111b29b48ae3.png)

**Comment by Blantados** [comment]
Compile with new commit. I forgot to remove FlxAnimate as that's still experimental.

**Comment by icaroleeb** [comment]
Yeah, I tried with latest commit, but it still doesn't work..

**Comment by CasualCypress** [comment]
same
