### ISSUE TITLE
compile error On lime build windows

### ISSUE THREAD

**Issue by Enchantedbooz** [Blantados/BETADCIU-Engine-Source#18]
source/luafiles/LuaClass.hx:40: characters 46-58 : Type not found : StatePointer

**Comment by Ryiuu04** [comment]
haxelib remove linc_luajit
haxelib remove hxvm_luajit
and then
haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by Enchantedbooz** [comment]
Thanks!!!! Ryiuu04

**Comment by Ryiuu04** [comment]
np!
